# Generated by Django 4.0.1 on 2022-02-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_seller_addressline1_alter_seller_addressline2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
